function figureHandle = makeReportCover(runs, summaryTable, style, visible)
%MAKEREPORTCOVER Create a compact machine-derived report cover page.
figureHandle = figure('Visible', visible, 'Color', 'white', ...
    'Position', [100, 100, 1100, 750]);
axesHandle = axes(figureHandle, 'Position', [0, 0, 1, 1], ...
    'Visible', 'off', 'XLim', [0, 1], 'YLim', [0, 1]);
text(axesHandle, 0.06, 0.93, ...
    sprintf('OpenArm pose-follow analysis report\n%d experiment(s)', numel(runs)), ...
    'FontSize', 22, 'FontWeight', 'bold', 'VerticalAlignment', 'top', ...
    'Interpreter', 'none');
text(axesHandle, 0.06, 0.82, ...
    'Structured evidence bundle for ChatGPT Work research logging', ...
    'FontSize', 12, 'Color', [0.25, 0.25, 0.25], ...
    'Interpreter', 'none');

allRows = summaryTable(summaryTable.phase == "all", :);
linesText = strings(height(allRows) + 1, 1);
linesText(1) = ["Experiment                     Samples   " + ...
    "Pos mean/RMS/p95/max (mm)   Ori mean/RMS/p95/max (deg)   IK A/F/S"];
for index = 1:height(allRows)
    row = allRows(index, :);
    linesText(index + 1) = sprintf( ...
        '%-28s %7d   %6.2f/%6.2f/%6.2f/%6.2f      %5.2f/%5.2f/%5.2f/%5.2f       %g/%g/%g', ...
        char(row.experiment), row.samples, ...
        row.tcp_position_mean_mm, row.tcp_position_rms_mm, ...
        row.tcp_position_p95_mm, row.tcp_position_max_mm, ...
        row.tcp_orientation_mean_deg, row.tcp_orientation_rms_deg, ...
        row.tcp_orientation_p95_deg, row.tcp_orientation_max_deg, ...
        row.ik_accepted, row.ik_failed, row.ik_superseded);
end
text(axesHandle, 0.06, 0.70, join(linesText, newline), ...
    'FontName', 'FixedWidth', 'FontSize', 10, ...
    'VerticalAlignment', 'top', 'Interpreter', 'none');

phaseLegend = strings(numel(style.phase_names), 1);
for index = 1:numel(style.phase_names)
    phaseLegend(index) = sprintf('%s = RGB(%.2f, %.2f, %.2f)', ...
        style.phase_names(index), style.phase_colors_rgb(index, :));
end
text(axesHandle, 0.06, 0.34, ...
    "Profile phase colors (used consistently):" + newline + ...
    join(phaseLegend, "    "), ...
    'FontSize', 10, 'VerticalAlignment', 'top', 'Interpreter', 'none');
text(axesHandle, 0.06, 0.16, ...
    ["Notes:"; ...
     "- Position errors are millimetres; orientation errors are degrees."; ...
     "- Statistics are mean, RMS, maximum, and linearly interpolated p95."; ...
     "- Legacy files without profile labels are reported as unlabeled."; ...
     "- Legacy signed projections are reconstructed from stored TCP positions."], ...
    'FontSize', 10, 'VerticalAlignment', 'top', 'Interpreter', 'none');
end
